language: cpp

compiler:
  - gcc

before_install:
  - echo $LANG
  - echo $LC_ALL
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq cmake libarmadillo-dev

script:
  - mkdir build && build && cmake .. && make

after_script:
  - ./main
