language: cpp
compiler:
- gcc
before_install:
- echo $LANG
- echo $LC_ALL
- wget https://cmake.org/files/v3.4/cmake-3.4.0-Linux-x86_64.tar.gz -q --no-check-certificate
- tar -xzvf cmake-3.4.0-Linux-x86_64.tar.gz
- wget http://sourceforge.net/projects/arma/files/armadillo-6.500.4.tar.gz -q --no-check-certificate
- tar -xzvf armadillo-6.500.4.tar.gz
- wget https://github.com/google/googletest/archive/release-1.7.0.zip -q --no-check-certificate
- unzip release-1.7.0.zip
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
- export PATH=$PWD/cmake-3.4.0-Linux-x86_64/bin/:$PATH
- cd armadillo-6.500.4 && cmake . && make && make install DESTDIR=./
- export PATH=$PWD/usr/include:$PWD/usr/lib:$PATH && cd ..
- cd googletest-release-1.7.0 && mkdir build && cd build && cmake -DBUILD_SHARED_LIBS=ON -G"Unix Makefiles" .. && make
- export PATH=$PWD/../include:$PWD:$PATH && cd ..
- cd ..
script:
- mkdir build && cd build
- cmake -DCMAKE_BUILD_TYPE=Release ..
- make
- "./runTest"
after_success:
- gnuplot ../plot.gp
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libopenblas-dev
    - libboost-all-dev
    - liblapack-dev
    - libarpack-dev
    - gcc-5
    - g++-5
    - gnuplot
notifications:
  email: false
sudo: false
before_deploy:
  - gem install mime-types -v 2.6.2
deploy:
  provider: releases
  api_key:
    secure: dqx7Gs+kEM/3PmCDwqjjotUn3LtJokidbJE8I0x/C1/mvR+1dXZWtWJ0dA2o1icx2LB0uoJaBNa/k1IfzRlnpG0gQm3etPirFO27iL730jjCSKVkaHOSIre0f/E8bWp4ekO+HgtQZ5tPtqshEiPb3cxwSsHMd5q2S3qKYfbiEnpJ5JYsmyaVYp3tX+YDmoo9D5C8wCDf71pVzDm17uXcgdHx9OppXxZa6Z3MLn/pTdc7D8HWQn6eNZF4FP512BQLga20MxiE/gMkjfgDjVfiAy4q1heizBRf3BkVqi2DQKtZOlMtz1Sm+WleGH8AEjiwZ9+9GbJTclGl+KZSKkm88F7eQRAtavMg19ctlTAkugcyceI85hwqdLmZqO9AFvrflQAhEIiaKA8faz0xCWfDXVoF5w98Iqvc3rY2NYXiGU5MBUgATb9XBecEQZEp9QlkD/LpRfaa7Tl97IpSh5eOnZBbkJAtSK2co9PZQegGg4ewIihIeAta5iwTa/KGhCU+wxPvjZkdazt6j0d/9OVZzKE8vcw8+4FYXA0Phtasu26piBn5lef/ihh8Yj+7sa86uQ7LJoNIQ3ZF4hLxuhUjBhDPvOmkCwKMEVgz29SxV04nPe7aZPDXLUJNxG0GsGv9kf/rJlFLQmo/QZi6dqnQ83PSix7j2+NsDfK104mHqGc=
  file:
    - "libls.so"
    - "runTest"
    - "signal_plot.jpg"
  skip_cleanup: true
  on:
    tags: true
