language: cpp

compiler:
  - gcc

before_install:
  - echo $LANG
  - echo $LC_ALL
  - wget https://cmake.org/files/v3.4/cmake-3.4.0-Linux-x86_64.tar.gz -q --no-check-certificate
  - tar -xzvf cmake-3.4.0-Linux-x86_64.tar.gz
  - wget http://sourceforge.net/projects/arma/files/armadillo-6.200.4.tar.gz -q --no-check-certificate
  - tar -xzvf armadillo-6.200.4.tar.gz


install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
- export PATH=$PWD/cmake-3.4.0-Linux-x86_64/bin/:$PATH
- cd armadillo-6.200.4 && cmake . && make && make install DESTDIR=./
- export PATH=$PWD/usr/include:$PWD/usr/lib:$PATH
- cd ..


script:
  - mkdir build && cd build
  - cmake ..
  - make

after_success:
  - ./main

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libopenblas-dev
    - liblapack-dev
    - libarpack-dev
    - gcc-5
    - g++-5
notifications:
  email: false
sudo: false
