language: cpp

compiler:
  - gcc

before_install:
  - echo $LANG
  - echo $LC_ALL
  - wget https://cmake.org/files/v3.4/cmake-3.4.0-Linux-x86_64.tar.gz -q --no-check-certificate
  - tar -xzvf cmake-3.4.0-Linux-x86_64.tar.gz
  - export PATH=$PWD/cmake-3.4.0-Linux-x86_64/bin/:$PATH

install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi

script:
  - mkdir build && cd build
  - cmake ..
  - make

after_success:
  - ./main

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libarmadillo-dev
    - gcc-5
    - g++-5
notifications:
  email: false
sudo: false
